
### tes
GET http://localhost:3000/tes
Accept: application/json

### get song
GET http://localhost:3000/api/song
Accept: application/json

### create song
POST http://localhost:3000/api/song
Accept: application/json
Content-Type: application/json

{
  "title": "Tes",
  "duration": 4,
  "artists": [
    {
      "name": "Ikhsan"
    }
  ],
  "url": "localhost"
}

### get song by Id
GET http://localhost:3000/api/song/2
Accept: application/json

### create playlist
POST http://localhost:3000/api/playlist
Accept: application/json
Content-Type: application/json

{
  "title": "Testi",
  "desc":  "tstopi",
  "songs": ["123", "12345"]
}

### get play count of song from playlist
GET http://localhost:3000/api/playlist/12/play-count
Accept: application/json